<?PHP

// Conexión a PostgreSQL.
$dbconn= pg_Connect( "host=localhost dbname=geodata user=postgres password=database" );
if( !$dbconn )
{
echo "En estos momentos no funciona el sistema!";
exit;
}

// Consulta a la tabla parcpcht en geodata.
$query = "SELECT area,idmza,parc,z_zonif FROM parcpcht WHERE circunsc = '$circ' and secc = '$secc' and quint ='$quin' and fracc = '$frac' and manz = '$manz' ORDER BY parc;";
$result = pg_Exec( $dbconn, $query );
$row = pg_Fetch_Row( $result, 0 );
$filtro = $row[1];
$parc = $row[2];
$superf = $row[0];

//Ubicación del map file
$map_path="c:/ms4w/apps/plancheta_digital/map/";
$map = ms_newMapObj($map_path."/planchetas1.map");

//para filtrar las parcelas
$layer= $map->getLayerByName('Parcelas');
$clasp = $layer->getClass('parcela');
$clasp->setExpression($filtro);

//para filtrar medidas
$layer1= $map->getLayerByName('Medidas');
$clasm = $layer1->getClass('medida');
$clasm->setExpression($filtro);

// Consulta a la tabla mza709 en geodata para el zoom.
$querybox = "SELECT minx,miny,maxx,maxy FROM mza709 WHERE idmza= '$filtro';";
$resultbox = pg_exec ($dbconn, $querybox);
$bbox= pg_Fetch_Row($resultbox, 0);
$minx= $bbox[0];
$miny= $bbox[1];
$maxx= $bbox[2];
$maxy= $bbox[3];

//Extensión de la vista a la manzana 
$map->setextent($minx-5,$miny-5,$maxx+5,$maxy+5);

//dibujar mapa
$image=$map->draw();
$image_url=$image->saveWebImage();
$escala=$map->drawScaleBar();
$escala_url=$escala->saveWebImage();

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
 <HEAD>
  <TITLE> Plancheta Digital - Municipalidad de Malvinas Argentinas </TITLE>
  <META NAME="Generator" CONTENT="EditPlus">
  <META NAME="Author" CONTENT="">
  <META NAME="Keywords" CONTENT="">
  <META NAME="Description" CONTENT="">
	<link href="css/estilos.css" rel="stylesheet" type="text/css"/>
	<link rel="icon" href="img/icon.gif" type="image/x-icon" />  
	<link rel="shortcut icon" href="img/icon.gif" type="image/x-icon" />
 </HEAD>
<BODY>
<div id="top">
	<div class="div70">
		<!--  -->
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				 <p class="titulo_item">Nomenclatura Catastral</p>
				 <p>
				 <label>Circ: <B><? echo "$circ"; ?></B></label><label>Secc: <B><? echo "$secc"; ?></B></label><label>Quinta: <B><? echo "$quin"; ?></B></label><label>Fracc: <B><? echo "$frac"; ?></B></label><label>Mza: <B><? echo "$manz"; ?></B></label><label>Id-Mza:<B><? echo "$filtro"; ?></B></label><label>Mza s/Tit.:<B>B</B></label>
				 </p>
				<p class="titulo_item">&nbsp;</p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->	
	</div>
	<div class="div30">
		<!--  -->
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				 <p>
				 <label>Partido: </label><B>Malvinas Argentinas</B><BR>
				 <label>Localidad:</label> <B>Grand Bourg</B><BR>
				 <label>Barrio: </label><B>Pami</B>
				 </p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->		
	</div>

</div>
<div id="contenido">
	<div class="div70">
	   <div class="roundedcornr_box_155118">
		  <div class="roundedcornr_top_155118"><div></div></div>
		  <div class="roundedcornr_content_155118"><p>
			 <BR><IMG SRC="<? echo $image_url; ?>" width="100%"><BR><!--  -->
				<!--  -->
		  </div>
		   <div class="roundedcornr_bottom_155118"><div></div></div>
		</div>

	</div>
	<div class="div30">
		<!--  -->
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				 <P class="titulo_item">Datos Parcelarios</p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				 <P class="boxH540">
				<TABLE>
				 <TR>
					<TH>Parc.</TH>
					<TH>Lote</TH>
					<TH>Sup.</TH>
					<TH>Zon.</TH>
					<TH>Parc.</TH>
					<TH>Lote</TH>
					<TH>Sup.</TH>
					<TH>Zon.</TH>
				 </TR>
					 <?PHP
					  if(!$row)
					   {
					   echo "Nomenclatura inexistente!";
					   exit;
					   }
					  else
					   {  
					   	$imprimir= pg_fetch_array($result);
						$item= array_slice($imprimir,0,10);
				        while($item)
				          {
				       ?>
					 <TR>
						<TD><?php echo "$item[2]"; ?></TD>
						<TD>2</TD>
						<TD><?php echo "$item[0]"; ?></TD>
						<TD><?php echo "$item[3]"; ?></TD>
					 </TR>
					 <?php
					    }
				         }
					  pg_Close( $dbconn );
					 ?>
				 </TABLE>
				 </P>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->
	</div>
</div><!-- /contenido -->
<div id="base">
		<div class="div33">
		<!--  -->
		<div class="roundedcornr_box_745872">
		   <div class="roundedcornr_top_745872"><div></div></div>
			  <div class="roundedcornr_content_745872">
				 <P class="titulo_itembox">Infraestructura de calles </p>
			  </div>
		   <div class="roundedcornr_bottom_745872"><div></div></div>
		</div>
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				 <P class="boxH180">
				<TABLE>
				 <TR>
					<TH>&nbsp;</TH>
					<TH>Calles</TH>
					<TH>Agua</TH>
					<TH>Gas</TH>
					<TH>Cloacas</TH>
					<TH>Calzada</TH>
				 </TR>
				 <TR>
					<TD>1023</TD>
					<TD>#nombre</TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD>#nombre</TD>
				 </TR>
				 <TR>
					<TD>1053</TD>
					<TD>#nombre</TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD>#nombre</TD>
				 </TR>
				 <TR>
					<TD>1663</TD>
					<TD>#nombre</TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD>#nombre</TD>
				 </TR>
				 <TR>
					<TD>1853</TD>
					<TD>#nombre</TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" checked></TD>
					<TD>#nombre</TD>
				 </TR>
				 <TR>
					<TD>0</TD>
					<TD>&nbsp;</TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD>&nbsp;</TD>
				 </TR>
				 <TR>
					<TD>0</TD>
					<TD>&nbsp;</TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD>&nbsp;</TD>
				 </TR>
				 <TR>
					<TD>0</TD>
					<TD>&nbsp;</TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD><INPUT TYPE="checkbox" NAME="" ></TD>
					<TD>&nbsp;</TD>
				 </TR>
				</TABLE>
				</p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->
		</div>
		<div class="div33">
		<!--  -->
		<div class="roundedcornr_box_689947">
		   <div class="roundedcornr_top_689947"><div></div></div>
			  <div class="roundedcornr_content_689947">
				 <P class="titulo_itembox">Equipamiento Urbano</p>
			  </div>
		   <div class="roundedcornr_bottom_689947"><div></div></div>
		</div>
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				<P class="boxH180">
				<TABLE>
				 <TR>
					<TH colspan="2">Distancias aproximadas en metros al equipamiento más cercano</TH>
				 </TR>
				 <TR>
					<TD width="50%">Centro de Salud</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Escuelas</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Est. FF.CC.</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Colectivos</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Esp. verdes</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Delegación</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 <TR>
					<TD width="50%">Seguridad</TD>
					<TD width="50%">#nombre</TD>
				 </TR>
				 </TABLE>
				</p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->
		</div>
		<div class="div33">
		<div class="roundedcornr_box_605328">
		   <div class="roundedcornr_top_605328"><div></div></div>
			  <div class="roundedcornr_content_605328">
				 <P class="titulo_itembox">Datos del Plano </p>
			  </div>
		   <div class="roundedcornr_bottom_605328"><div></div></div>
		</div>
		<div class="roundedcornr_box_914194">
		   <div class="roundedcornr_top_914194"><div></div></div>
			  <div class="roundedcornr_content_914194">
				  <P class="boxH180">
				<TABLE>
				 <TR>
					<TH colspan="3">Planos</TH>
				 </TR>
				 <TR>
					<TD width="33%"><B>Origen:</B></TD>
					<TD width="33%">48-11-1972</TD>
					<TD width="33%">Pc. 1 a 32</TD>
				 </TR>
				 <TR>
					<TD width="33%"><B>Modificatorio</B></TD>
					<TD width="33%">133-04-2007</TD>
					<TD width="33%">Pc. 1 a 20</TD>
				 </TR>
				 <TR>
					<TD width="33%">&nbsp;</TD>
					<TD width="33%">133-05-2007</TD>
					<TD width="33%">Pc. 20 a 32</TD>
				 </TR>
				 <TR>
					<TD width="33%">Ph</TD>
					<TD width="33%">133-05-2008</TD>
					<TD width="33%">Pc. 1 - 2</TD>
				 </TR>
				 </TABLE><BR><BR>
				 <TABLE>
				 <TR>
					<TH colspan="3">Observaciones</TH>
				 </TR>
				 <TR>
					<TD width="50%">Pc 2</TD>
					<TD width="50%">Se anexa a 2</TD>
				 </TR>
				 <TR>
					<TD width="50%">Pc 5</TD>
					<TD width="50%">Urban</TD>
				 </TR>
				 </TABLE>
				  </p>
			  </div>
		   <div class="roundedcornr_bottom_914194"><div></div></div>
		</div>
		<!--  -->
		</div>
</div>
 </BODY>
</HTML>

