<!DOCTYPE html>
<?php
 include("seguridad.php");


?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="bootstrap3/assets/ico/favicon.png">

    <title>Plancheta Digital - Municipalidad de Malvinas Argentinas</title>

    <!-- Bootstrap core CSS -->
    <link href="bootstrap3/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="index.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

    <!--  <FORM ACTION="plncht_nv.phtml" METHOD="POST" class="form-signin"> -->
      <form ACTION="plncht_nv.phtml" METHOD="POST" class="form-signin">
        <h2 class="form-signin-heading">Complete el siguiente formulario: </h2><br><br>
        <input type="number" min= "1" max= "9" class="form-control" maxlength= "1" NAME="circ" placeholder="Circunscripción" required autofocus>
        <input type="text" maxlength= "1" onblur="this.value=this.value.toUpperCase()" class="form-control" NAME="secc" placeholder="Sección" required>
        <input type="text" class="form-control" NAME="quin" placeholder="Quinta" required>
        <input type="text" class="form-control" NAME="frac" placeholder="Fracción" required>
        <input type="text" class="form-control" NAME="manz" placeholder="Manzana" required><br>
        <!--<script type="text/javascript">
        alert("Usted ha ingresado correctamente :D");
        </script> -->
        <button class="btn btn-lg btn-primary btn-block" type="submit">Consultar plancheta</button>
      </form>

    </div> <!-- /container -->
	<div>
	<h2>Usted es:<? echo $_SESSION['usuarioactual']; ?> </h2><br>
	</div>
	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>
